### ISSUE TITLE
Exception:MQClientNetworkException ("NetWorkException", "Remote end closed connection without response")

### ISSUE THREAD

**Issue by qizai123** [aliyunmq/mq-http-python-sdk#6]
mq-http-python-sdk V1.0.1 Samples Publish Message

Publish Message Fail. Exception:MQClientNetworkException ("NetWorkException", "Remote end closed connection without response")

根据要求填写相关验证信息，但是始终异常

**Comment by lihongyiyi** [comment]
请问，这个问题最后是如何解决的

**Comment by JoshYuJump** [comment]
Save issue

**Comment by willdonggg** [comment]
我也遇到这个问题，原因是用的是tcp的endpoint地址，改成http的就可以了
