### ISSUE TITLE
The length of message tag should be between 1 and 16

### ISSUE THREAD

**Issue by larryhq** [aliyunmq/mq-http-python-sdk#7]
阿里云添加tag的时候没有规定长度是多少，这里为什么要限制message_tag的长度？和其他版本的SDK也不一样

**Comment by xusk** [comment]
把源码改了吧

**Comment by SCNieh** [comment]
fixed in https://github.com/aliyunmq/mq-http-python-sdk/commit/1da73f0f058dfe9380faf4d1e6fd1c75d0b21c24
